server:
  port: 8888
spring:
  application:
    name: things
  datasource:
    url: jdbc:postgresql://localhost:5432/ithings
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
springdoc:
  api-docs:
    path: /docs
    pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true
    #disable-swagger-default-url: true
    path: /docs-ui