server:
  port: 8888
spring:
  application:
    name: ithings
  datasource:
    url: jdbc:postgresql://localhost:5432/ithings
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true